src/SkyAthlon/SkyBall2016Bundle/Entity/Round.php
<?php

namespace SkyAthlon\SkyBall2016Bundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Round
 *
 * @ORM\Table(name="skyball2016_round")
 * @ORM\Entity(repositoryClass="SkyAthlon\SkyBall2016Bundle\Repository\RoundRepository")
 */
class Round
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
    protected $name;

    /**
     * @var int
     *
     * @ORM\Column(name="number", type="smallint", unique=true)
     */
    protected $number;

    /**
     * @ORM\OneToMany(targetEntity="Game", mappedBy="round")
     */
    protected $games;

    /**
     * @ORM\OneToMany(targetEntity="RoundResult", mappedBy="round")
     */
    protected $roundResults;

    /**
     * @ORM\OneToMany(targetEntity="RoundKerchiefResult", mappedBy="round")
     */
    protected $roundKerchiefResults;

    /**
     * @ORM\OneToMany(targetEntity="PlayerResult", mappedBy="game")
     */
    protected $playerResults;

    /**
     * @ORM\Column(name="closed", type="boolean", nullable=true)
     */
    protected $closed;

    /**
     * @ORM\Column(name="reversed", type="boolean", nullable=true)
     */
    protected $reversed;

    /**
     * @ORM\Column(name="playoffs", type="boolean", nullable=true)
     */
    protected $playoffs;

    /**
     * @ORM\ManyToOne(targetEntity="Team", inversedBy="hostedRounds")
     * @ORM\JoinColumn(name="host_id", referencedColumnName="id")
     */
    protected $host;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    protected $date;

    public function __toString() {
        return $this->name;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->games = new ArrayCollection();
        $this->playerResults = new ArrayCollection();
        $this->roundResults = new ArrayCollection();
        $this->roundKerchiefResults = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Round
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set number
     *
     * @param integer $number
     *
     * @return Round
     */
    public function setNumber($number)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Get number
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Add game
     *
     * @param Game $game
     *
     * @return Round
     */
    public function addGame(Game $game)
    {
        $this->games[] = $game;

        return $this;
    }

    /**
     * Remove game
     *
     * @param Game $game
     */
    public function removeGame(Game $game)
    {
        $this->games->removeElement($game);
    }

    /**
     * Get games
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGames()
    {
        return $this->games;
    }

    /**
     * Add playerResult
     *
     * @param PlayerResult $playerResult
     *
     * @return Round
     */
    public function addPlayerResult(PlayerResult $playerResult)
    {
        $this->playerResults[] = $playerResult;

        return $this;
    }

    /**
     * Remove playerResult
     *
     * @param PlayerResult $playerResult
     */
    public function removePlayerResult(PlayerResult $playerResult)
    {
        $this->playerResults->removeElement($playerResult);
    }

    /**
     * Get playerResults
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPlayerResults()
    {
        return $this->playerResults;
    }

    /**
     * Set closed
     *
     * @param boolean $closed
     *
     * @return Round
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;

        return $this;
    }

    /**
     * Get closed
     *
     * @return boolean
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Add roundResult
     *
     * @param RoundResult $roundResult
     *
     * @return Round
     */
    public function addRoundResult(RoundResult $roundResult)
    {
        $this->roundResults[] = $roundResult;

        return $this;
    }

    /**
     * Remove roundResult
     *
     * @param RoundResult $roundResult
     */
    public function removeRoundResult(RoundResult $roundResult)
    {
        $this->roundResults->removeElement($roundResult);
    }

    /**
     * Get roundResults
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRoundResults()
    {
        return $this->roundResults;
    }

    /**
     * Add roundKerchiefResult
     *
     * @param RoundKerchiefResult $roundKerchiefResult
     *
     * @return Round
     */
    public function addRoundKerchiefResult(RoundKerchiefResult $roundKerchiefResult)
    {
        $this->roundKerchiefResults[] = $roundKerchiefResult;

        return $this;
    }

    /**
     * Remove roundKerchiefResult
     *
     * @param RoundKerchiefResult $roundKerchiefResult
     */
    public function removeRoundKerchiefResult(RoundKerchiefResult $roundKerchiefResult)
    {
        $this->roundKerchiefResults->removeElement($roundKerchiefResult);
    }

    /**
     * Get roundKerchiefResults
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRoundKerchiefResults()
    {
        return $this->roundKerchiefResults;
    }

    /**
     * Set reversed
     *
     * @param boolean $reversed
     *
     * @return Round
     */
    public function setReversed($reversed)
    {
        $this->reversed = $reversed;

        return $this;
    }

    /**
     * Get reversed
     *
     * @return boolean
     */
    public function getReversed()
    {
        return $this->reversed;
    }

    /**
     * Set host
     *
     * @param Team $host
     *
     * @return Round
     */
    public function setHost(Team $host = null)
    {
        $this->host = $host;

        return $this;
    }

    /**
     * Get host
     *
     * @return Team
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Round
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set playoffs
     *
     * @param boolean $playoffs
     *
     * @return Round
     */
    public function setPlayoffs($playoffs)
    {
        $this->playoffs = $playoffs;

        return $this;
    }

    /**
     * Get playoffs
     *
     * @return boolean
     */
    public function getPlayoffs()
    {
        return $this->playoffs;
    }
    
    public function getFullName() {
    	$str = $this->name;
    	if ($this->date && strpos($this->date->format('Y'), '-000') === false) {
    		$str .= ' (' . $this->date->format('Y.m.d');
    		
    		if ($this->host) {
    			$str .= ' - hg: ' . $this->host;
    		}
    		
    		$str .= ')';
    	}
    	else if ($this->host) {
    			$str .= ' (hg: ' . $this->host . ')';
    	}
    	return $str;
    }
}

src/SkyAthlon/SkyBall2016Bundle/Controller/Round/RoundGameController.php
<?php

namespace SkyAthlon\SkyBall2016Bundle\Controller\Round;

use AppBundle\Entity\Settings;
use SkyAthlon\SkyBall2016Bundle\Entity\Game;
use SkyAthlon\SkyBall2016Bundle\Entity\PlayerResult;
use SkyAthlon\SkyBall2016Bundle\Entity\Round;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Round controller.
 *
 * @Route("/skyball-2016/fordulo")
 */
class RoundGameController extends Controller
{

    /**
     * Displays a form to edit an existing Game entity.
     *
     * @Route("/{roundid}/merkozes/uj/", name="skyball2016_game_new")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param $roundid
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function newGameAction(Request $request, $roundid)
    {
        if ($this->getUser()) {
            $em = $this->getDoctrine()->getManager();

            /** @var Round $round */
            $round = $em->getRepository('SkyAthlonSkyBall2016Bundle:Round')->findOneBy(array(
                'number' => $roundid,
            ));

            if (($this->getUser()->isAdmin() && !$round->getClosed() && $round->getPlayoffs()) || $this->getUser()->isSu()) {
                $game = new Game();

                $games = $em->getRepository('SkyAthlonSkyBall2016Bundle:Game')->findBy(array(
                    'round' => $round,
                ));
                $arr = array(
                    'attr' => $games,
                );

                $form = $this->createForm('SkyAthlon\SkyBall2016Bundle\Form\GameType', $game, $arr);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $gameType = $form['gameType']->getData();

                    $game->setWeight($gameType->getWeight());
                    $game->setRound($round);

                    $em->persist($game);

                    $em->flush();

                    $messageService = $this->get('skyathlon_message');
                    $messageService->setMessage('flashbag.skyball2016.game.created');

                    if ($game->getTeamA() && $game->getTeamB()) {
                        $playerService = $this->get('skyball2016_player');
                        $playerService->getKerchiefs($game);
                    }

                    if (!$game->getPointA() && !$game->getPointB() && !$game->isPreGame() && $game->getTeamA() && $game->getTeamB()) {
                        return $this->redirectToRoute('skyball2016_game_edit_player_stats', array('roundid' => $roundid, 'game' => $game->getId()));
                    }

                    $anchor = '#' . $game->getGameType()->getComputerName();
                    return $this->redirect($this->generateUrl('skyball2016_round', array('round' => $roundid)) . $anchor);
                }

                return array(
                    'game' => $game,
                    'roundid' => $roundid,
                    'form' => $form->createView(),
                );
            }
            else {
                return $this->redirectToRoute('skyball2016_round', array('round' => $roundid));
            }
        }
        else {
            return $this->redirectToRoute('index');
        }
    }

    /**
     * Displays a form to edit an existing Game entity.
     *
     * @Route("/{roundid}/merkozes/{game}/szerkesztes/", name="skyball2016_game_edit")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param $roundid
     * @param Game $game
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function editGameAction(Request $request, $roundid, Game $game)
    {
        if ($this->getUser()) {
            $em = $this->getDoctrine()->getManager();

            /** @var Round $round */
            $round = $em->getRepository('SkyAthlonSkyBall2016Bundle:Round')->findOneBy(array(
                'number' => $roundid,
            ));

            if (($this->getUser()->isAdmin() && !$round->getClosed()) || $this->getUser()->isSu()) {
                $oldTeamA = $game->getTeamA();
                $oldTeamB = $game->getTeamB();

                $games = $em->getRepository('SkyAthlonSkyBall2016Bundle:Game')->findBy(array(
                    'round' => $round,
                ));
                $arr = array(
                    'attr' => $games,
                );

                $editForm = $this->createForm('SkyAthlon\SkyBall2016Bundle\Form\GameType', $game, $arr);
                $editForm->handleRequest($request);

                if ($editForm->isSubmitted() && $editForm->isValid()) {
                    $weight = $round->getReversed() ? $game->getGameType()->getReversedWeight() : $game->getGameType()->getWeight();
                    $game->setWeight($weight);
                    $em->persist($game);

                    if (!($game->getTeamA() === $oldTeamA && $game->getTeamB() === $oldTeamB)) {
                        $playerResults = $em->getRepository('SkyAthlonSkyBall2016Bundle:PlayerResult')->findBy(array(
                            'game' => $game,
                        ));

                        foreach ($playerResults as $playerResult) {
                            $em->remove($playerResult);
                        }
                    }

                    /** @var Settings $currentGameObject */
                    $currentGameObject = $this->getDoctrine()->getManager()->getRepository('AppBundle:Settings')->findOneBy(array(
                        'name' => 'skyball2016_currentGame',
                    ));
                    $isCurrent = $editForm->get('current')->getData();
                    if ($isCurrent) {
                        if (!$currentGameObject) {
                            $currentGameObject = new Settings();
                            $currentGameObject->setName('skyball2016_currentGame');
                        }

                        $currentGameObject->setValue($game->getId());
                        $em->persist($currentGameObject);
                    }
                    elseif ($currentGameObject && $currentGameObject->getValue() == $game->getId()) {
                        $currentGameObject->setValue(0);
                        $em->persist($currentGameObject);
                    }

                    $em->flush();

                    $messageService = $this->get('skyathlon_message');
                    $messageService->setMessage('flashbag.skyball2016.game.edited');

                    if ($game->getTeamA() && $game->getTeamB()) {
                        $playerService = $this->get('skyball2016_player');
                        $playerService->getKerchiefs($game);
                    }

                    if (!$game->getPointA() && !$game->getPointB() && !$game->isPreGame() && $game->getTeamA() && $game->getTeamB()) {
                        return $this->redirectToRoute('skyball2016_game_edit_player_stats', array('roundid' => $roundid, 'game' => $game->getId()));
                    }

                    $anchor = '#' . $game->getGameType()->getComputerName();
                    return $this->redirect($this->generateUrl('skyball2016_round', array('round' => $roundid)) . $anchor);
                }

                $form = $this->createDeleteGameForm($roundid, $game);

                return array(
                    'game' => $game,
                    'roundid' => $roundid,
                    'edit_form' => $editForm->createView(),
                    'delete_form' => $form->createView(),
                );
            }
            else {
                return $this->redirectToRoute('skyball2016_round', array('round' => $roundid));
            }
        }
        else {
            return $this->redirectToRoute('index');
        }
    }

    /**
     * Displays a form to edit the players stats for a game.
     *
     * @Route("/{roundid}/merkozes/{game}/jatekos-statisztika/szerkesztes/", name="skyball2016_game_edit_player_stats")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param $roundid
     * @param Game $game
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function editPlayerStatsAction(Request $request, $roundid, Game $game)
    {
        if ($this->getUser()) {
            $em = $this->getDoctrine()->getManager();

            /** @var Round $round */
            $round = $em->getRepository('SkyAthlonSkyBall2016Bundle:Round')->findOneBy(array(
                'number' => $roundid,
            ));

            if ((($this->getUser()->isAdmin() && !$round->getClosed()) || $this->getUser()->isSu()) && !$game->isPreGame() && $game->getTeamA() && $game->getTeamB()) {
                $values = array();

                $current = false;
                $currentGameObject = $em->getRepository('AppBundle:Settings')->findOneBy(array(
                    'name' => 'skyball2016_currentGame'
                ));

                if ($currentGameObject && $currentGameObject->getValue() == $game->getId()) {
                    $current = true;
                }

                if ($request->getMethod() === 'POST') {
                    $values = $request->request->all();
                    $recalc = false;
                    $hasCurrent = false;

                    foreach ($values as $id => $value) {
                        if ($id === 'recalc') {
                            $recalc = true;
                        }

src/SkyAthlon/SkyBall2016Bundle/Resources/views/Round/RoundPlayer/editRoundPlayerStats.html.twig
{% extends 'SkyAthlonSkyBall2016Bundle::base.html.twig' %}

{% block body %}
    <h1>{{ 'skyball2016.round.editPlayerStats' | trans({'%roundid%': roundid}) }}</h1>

    <form name="game_teamstats" method="post" action="{{ path('skyball2016_round_edit_player_stats', {roundid: roundid}) }}">
        <table id="round-players-table-{{ roundid }}" class="round-game-table round-teams-table round-players-table table-bordered table-hover table-condensed">
            <thead class="table-info">
            <tr>
                <th>{% trans %}skyball2016.kerchief.kerchief{% endtrans %}</th>
                <th>{% trans %}skyball2016.player.player{% endtrans %}</th>
            </tr>
            </thead>

            <tbody id="round-players-tbody-{{ roundid }}">
            {% for kctype,kcwinners in rankings['ret'] %}
                {% set trClass = '' %}
                {% if rankings['kcEgal'][kctype] == true %}
                    {% set trClass = 'egal' %}
                {% endif %}
                <tr id="round-team-{{ roundid }}-{{ kctype }}" class="{{ trClass }}">
                    <td>
                        <label for="round-player-{{ kctype }}">{{ kctype }}</label>{{ kctype }}
                    </td>
                    <td class="round-player-td round-game-player-right" id="round-player-td-{{ roundid }}-p">
                        <select class="round-player-select" id="round-player-{{ kctype }}" name="round-player-{{ kctype }}">
                            {% set nullSelected = '' %}
                            {% for id,player in kcwinners %}
                                {% set selected = '' %}
                                {% if rankings['kcValues'][kctype] == player.id %}
                                    {% set selected = 'selected' %}
                                {% endif %}

                                {% if player.id == -1 %}
                                    {% if rankings['kcValues'][kctype] == -1 %}
                                        {% set nullSelected = 'selected' %}
                                    {% endif %}
                                {% else %}
                                    <option {{ selected }} value="{{ player.id }}"
                                        data-data='{"number": "{{ players[player.id].number }}",
                                        "name": "{{ players[player.id].name }}",
                                        "team": "{{ players[player.id].team.computerName }}-select",
                                        "score": "{{ rankings['kerchiefs'][player.id][kctype] }}"}'
                                    >
                                        <span class="edit-player-number">{{ players[player.id].number }}</span>
                                        <span class="edit-player-name">{{ players[player.id].name }}</span>
                                        <span class="edit-player-score">({{ rankings['kerchiefs'][player.id][kctype] }})</span>
                                    </option>
                                {% endif %}
                            {% endfor %}
                            <option {{ nullSelected }} value="-1" data-data='{"isnull": "true"}'>
                                <span class="edit-player-number">?</span>
                                <span class="edit-player-name">?</span>
                                <span class="edit-player-score"></span>
                            </option>
                        </select>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-success pull-left" type="submit">
            <span class="glyphicon glyphicon-ok"></span> {% trans %}app.submit{% endtrans %}
        </button>
    </form>

    <a href="{{ path('skyball2016_round_players', {round: roundid}) }}" class="btn btn-primary pull-right">
        <span class="glyphicon glyphicon-arrow-left"></span> {% trans %}skyball2016.round.back{% endtrans %}
    </a>
    <div style="clear: both; height: 400px;"></div>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/css/selectize.min.css" />
{% endblock %}

{% block javascripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.min.js"></script>
    {% javascripts '@SkyAthlonSkyBall2016Bundle/Resources/public/js/selectize.js' filter='jsqueeze' output='js/skyball2016_selectize.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/SkyAthlon/SkyBall2016Bundle/Resources/views/Round/RoundPlayer/indexPlayers.html.twig
{% extends 'SkyAthlonSkyBall2016Bundle::base.html.twig' %}

{% block body %}
    <h1>{% trans %}skyball2016.round.rounds{% endtrans %}</h1>

    <div id="round-navigation" class="navigation">
        {{ knp_pagination_render(rounds) }}
    </div>

    {% for round in rounds %}
        <script>
            var isPlayoffs = {{ round.playoffs ? 'true' : 'false'}};
        </script>
        <div id="round-stats" class="navigation">
            {% if not round.playoffs %}
                <a class="btn btn-default" href="{{ path('skyball2016_round_teams', {round: round.number}) }}">
                    {% trans %}skyball2016.round.menuSummary{% endtrans %}
                </a>
            {% endif %}
            <a class="btn btn-default" href="{{ path('skyball2016_round', {round: round.number}) }}">
                {% trans %}skyball2016.round.menuGames{% endtrans %}
            </a>
            <a class="btn btn-primary" href="{{ path('skyball2016_round_players', {round: round.number}) }}">
                {% trans %}skyball2016.round.menuPlayers{% endtrans %}
            </a>
        </div>

        <div id="round-{{ round.id }}" class="round-item">
            <div class="round-head">
                <h2 class="round-title">{{ 'skyball2016.round.playerStats' | trans({'%round%': round.fullName }) }}</h2>
            </div>

            {% if app.user %}
                {% if (app.user.isAdmin and not round.closed and not round.playoffs) or app.user.isSu %}
                    <a style="margin: 10px;" href="{{ path('skyball2016_round_edit_player_stats', {roundid: round.number}) }}" class="round-edit btn btn-primary pull-right">
                        <span class="glyphicon glyphicon-edit"></span> {% trans %}skyball2016.round.editPlayersButton{% endtrans %}
                    </a>
                {% endif %}
            {% endif %}
        
            <button id="print" class="btn btn-warning pull-right print-small print" data-print="top3" data-title="{{ 'skyball2016.round.playerStatsTop3' | trans({ '%round%': round.fullName }) }}">
                <i class="fa fa-print" aria-hidden="true"></i> {% trans %}app.print{% endtrans %}
            </button>

            <div class="round-head">
                <h2 class="round-title">{% trans %}skyball2016.round.playerStatsTop3Short{% endtrans %}</h2>
            </div>

            <div class="round-body clearfix top3" style="overflow-x: auto; padding: 0 10px;">
                <table id="round-players-top3-table-{{ round.id }}" class="round-top3-table round-game-table table table-bordered table-hover table-condensed">
                    <thead class="table-info">
                    <tr>
                    	<th></th>
                        {% for kcType in kcTypes %}
                            <th class="centered">{{ kcType.computerName }} <span class="kerchief-small">{{ kcType.name }}</span></th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    	{% for j in 0..9 %}
                        	<tr>
                        		<td class="centered"><b>{{ j + 1 }}</b></td>
                        		{% for kerchief, values in rankings.ret %}
                        			{% set vals = values[j] %}
                                	<td class="round-player-td {{ players[vals.id].team.computerName }}-select">
                                    	<span class="player-number">{{ players[vals.id].number }}</span>
                                    	<span class="player-name">{{ players[vals.id].name }}</span>
                                    	(<span class="player-score">{{ vals.val }}</span>)
                                	</td>
                            	{% endfor %}
                        	</tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <button id="print1" class="btn btn-warning pull-right print-small print" data-print="PrintArea" data-title="{{ 'skyball2016.round.playerStats' | trans({'%round%': round.fullName }) }}">
                <i class="fa fa-print" aria-hidden="true"></i> {% trans %}app.print{% endtrans %}
            </button>

            <div class="round-head">
                <h2 class="round-title">{% trans %}skyball2016.round.playerStatsAllShort{% endtrans %}</h2>
            </div>

            <div class="round-body clearfix PrintArea" style="overflow-x: auto">
                <table id="round-players-table-{{ round.id }}" class="round-game-table round-round-table table table-bordered table-hover table-condensed">
                    <thead class="table-info">
                    <tr>
                        <th>{% trans %}skyball2016.round.player{% endtrans %}</th>
                        {% for kcType in kcTypes %}
                            <th class="centered">{{ kcType.computerName }} <span class="kerchief-small">{{ kcType.name }}</span></th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for pid, kerchief in kerchiefs %}
                        <tr class="{{ players[pid].team.computerName }}">
                            <td class="round-player-td">
                                <span class="sortby">{{ players[pid].number }}</span>
                                <span class="player-number">{{ players[pid].number }}</span>
                                <b>{{ players[pid].name }}</b>
                            </td>
                            {% for i, kc in kerchief %}
                                {% set val = kc %}
                                {% if val == kcValues[i] %}
                                    {% set val = '<b>' ~ kc ~ '</b>' %}
                                {% endif %}
                                <td class="centered">{{ val | raw }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            {% if not round.playoffs %}
                <button id="print2" class="btn btn-warning pull-right print-big print" data-print="kerchiefs" data-title="{{ 'skyball2016.round.playerKerchiefs' | trans({ '%round%': round.fullName }) }}">
                    <i class="fa fa-print" aria-hidden="true"></i> {% trans %}app.print{% endtrans %}
                </button>

                <div class="round-head">
                    <h2 class="round-title">{% trans %}skyball2016.kerchief.kerchiefs{% endtrans %}</h2>
                </div>

                <div class="round-body kerchiefs">
                    <table id="round-teams-table-{{ round.id }}" class="round-game-table round-players-table round-teams-table table-bordered table-hover table-condensed">
                        <thead class="table-info">
                        <tr>
                            <th>{% trans %}skyball2016.kerchief.kerchief{% endtrans %}</th>
                            <th>{% trans %}skyball2016.player.player{% endtrans %}</th>
                            <th>{% trans %}skyball2016.kerchief.sum{% endtrans %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for kctype,pid in rankings['kcValues'] %}
                            {% set team = '' %}
                            {% set number = '?' %}
                            {% set name = '?' %}
                            {% set score = '' %}
                            {% if pid != '-1' %}
                                {% set team = players[pid].team.computerName %}
                                {% set number = players[pid].number %}
                                {% set name = players[pid].name %}
                                {% set score = rankings['kerchiefs'][pid][kctype] %}
                            {% endif %}

                            <tr class="{{ team }}">
                                <td class="round-game-team-left">{{ kctype }}</td>
                                <td class="round-team-td round-game-team-right {{ kctype }}">
                                    <span class="edit-player-number">{{ number }}</span>
                                    <span class="edit-player-name">{{ name }}</span>
                                </td>
                                <td>
                                    <span class="edit-player-score">{{ score }}</span>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}